[versions]
coil = "3.0.0-alpha06"
kotlin = "2.0.0"
compose = "1.7.0"
agp = "8.5.0"
voyager = "1.1.0-beta02"
koin = "3.5.6"
ktor = "2.3.12"
sqldelight = "2.0.2"
coroutines = "1.8.1"

[libraries]
coil-compose = { module = "io.github.qdsfdhvh:coil-compose", version.ref = "coil" }
coil-network = { module = "io.github.qdsfdhvh:coil-network-ktor", version.ref = "coil" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
